# Some parameters are shared among different steps, so we use YAML anchors and references to avoid duplication.
# Syntax : &anchor_name value  (define an anchor)
#          *anchor_name       (reference an anchor)

_shared:
  input_dir: &input_dir 'path\to\fits'
  moon_registered_dir: &moon_registered_dir 'path\to\moon_registered'
  sun_registered_dir: &sun_registered_dir 'path\to\sun_registered'
  moon_stacks_dir: &moon_stacks_dir 'path\to\moon_stacks'
  sun_stacks_dir: &sun_stacks_dir 'path\to\sun_stacks'
  moon_hdr_dir: &moon_hdr_dir 'path\to\moon_hdr'
  sun_hdr_dir: &sun_hdr_dir 'path\to\sun_hdr'
  merged_hdr_dir: &merged_hdr_dir 'path\to\merged_hdr'
  group_keywords: &group_keywords ["EXPTIME"]
  image_scale: &image_scale 1.00

registration:
  input_dir: *input_dir
  ref_filename: 'path\to\reference_image.fits'
  anchor_filenames: ['path\to\anchor_image.fits']
  moon_registered_dir: *moon_registered_dir
  sun_registered_dir: *sun_registered_dir
  image_scale: *image_scale
  clipped_factor: 1.3
  edge_factor: 1.0
  sigma_high_pass_tangential: 4.0
  max_iter: 10
  error_overlay_opacity: 0.75

moon_integration:
  moon_registered_dir: *moon_registered_dir
  moon_stacks_dir: *moon_stacks_dir
  group_keywords: *group_keywords

sun_integration:
  sun_registered_dir: *sun_registered_dir
  sun_stacks_dir: *sun_stacks_dir
  group_keywords: *group_keywords
  image_scale: *image_scale
  extra_radius_pixels: 2
  smoothness: 10.0

moon_hdr_composition:
  moon_stacks_dir: *moon_stacks_dir
  moon_hdr_dir: *moon_hdr_dir
  group_keywords: *group_keywords
  low_clipping_threshold: 0.005
  low_smoothness: 0.001
  high_clipping_threshold: 0.1 # if exptimes[i+1]/exptimes[i] = k, then we should have high/low << k
  high_smoothness: 0.01

sun_hdr_composition:
  sun_stacks_dir: *sun_stacks_dir
  sun_hdr_dir: *sun_hdr_dir
  moon_registered_dir: *moon_registered_dir
  group_keywords: *group_keywords
  image_scale: *image_scale
  extra_radius_pixels: 10
  low_clipping_threshold: 0.005
  low_smoothness: 0.001
  high_clipping_threshold: 0.1 # if exptimes[i+1]/exptimes[i] = k, then we should have high/low << k
  high_smoothness: 0.01

merge_sun_moon:
  sun_hdr_dir: *sun_hdr_dir
  moon_hdr_dir: *moon_hdr_dir
  merged_hdr_dir: *merged_hdr_dir
  sigma: 2
  moon_threshold: 0.002