# Some parameters are shared among different steps, so we use YAML anchors and references to avoid duplication.
# Syntax : &anchor_name value  (define an anchor)
#          *anchor_name       (reference an anchor)

_shared:
  - &raw_dir 'path/to/raw'
  - &fits_dir 'path/to/fits'
  - &moon_registered_dir 'path/to/moon_registered'
  - &sun_registered_dir 'path/to/sun_registered'
  - &stacks_dir 'path/to/stacks'
  - &group_keywords ["EXPTIME"]
  - &image_scale 1.00

conversion:
  raw_dir: *raw_dir
  fits_dir: *fits_dir
  flat_path: 'path/to/flats' # directory, master file, or null
  bias_path: 'path/to/bias'  # directory, master file, or null
  dark_path: 'path/to/dark'  # directory, master file, or null
  debayer_algorithm: 'bilinear' # or 'malvar', 'menon'
  calibration_outlier_threshold: null
  save_master: true

registration:
  fits_dir: *fits_dir
  ref_filename: 'path/to/reference_image.fits'    # or null to auto-select
  anchor_filenames: ['path/to/anchor_image.fits'] # or null to auto-select
  moon_registered_dir: *moon_registered_dir
  sun_registered_dir: *sun_registered_dir
  group_keywords: *group_keywords
  image_scale: *image_scale
  clipped_factor: 1.3
  edge_factor: 1.0
  sigma_high_pass_tangential: 4.0
  max_iter: 10
  error_overlay_opacity: 0.75

integration:
  moon_registered_dir: *moon_registered_dir
  sun_registered_dir: *sun_registered_dir
  stacks_dir: *stacks_dir
  group_keywords: *group_keywords
  outlier_threshold: 3
  rejection_extra_radius: 2
  rejection_smoothness: 10.0
  blend_smoothness: 3.0